name: "Azure VM Control"
description: "A GitHub action that starts and stops Azure virtual machines. Useful for controlling virtual machines used as GitHub self-hosted runners."
author: "Teqniqly"
inputs:
  azure_resource_group_name:
    description: "Azure resource group containing the VM"
    required: true
  azure_vm_name:
    description: "Name of the Azure VM"
    required: true
  azure_credentials:
    description: "Azure credentials JSON for azure/login"
    required: true
  operation:
    description: "VM operation to perform: start or deallocate"
    required: false
    default: "start"   # start | deallocate

runs:
  using: "composite"
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        missing_inputs=()

        if [ -z "$INPUT_AZURE_RESOURCE_GROUP_NAME" ]; then
            missing_inputs+=("azure_resource_group_name")
        fi

        if [ -z "$INPUT_AZURE_VM_NAME" ]; then
            missing_inputs+=("azure_vm_name")
        fi

        if [ -z "$INPUT_AZURE_CREDENTIALS" ]; then
            missing_inputs+=("azure_credentials")
        fi

        if [ ${#missing_inputs[@]} -ne 0 ]; then
            echo "Missing required inputs: ${missing_inputs[*]}"
            echo "Please configure these inputs in your repository settings."
            exit 1
        fi

        op="$INPUT_OPERATION"

        if [ "$op" != "start" ] && [ "$op" != "deallocate" ]; then
          echo "operation must be 'start' or 'deallocate', got: $op"
          exit 1
        fi

        echo "All required inputs are configured. Operation: $op"

    - name: Azure login
      uses: azure/login@8c334a195cbb38e46038007b304988d888bf676a
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Execute VM operation
      shell: bash
      run: |
        set -euo pipefail

        echo "Resource group: $INPUT_AZURE_RESOURCE_GROUP_NAME"
        echo "VM name: $INPUT_AZURE_VM_NAME"
        echo "Requested operation: $INPUT_OPERATION"

        if [ "$INPUT_OPERATION" = "start" ]; then
          echo "Checking current VM power state..."
          state=$(az vm show -d -g "$INPUT_AZURE_RESOURCE_GROUP_NAME" -n "$INPUT_AZURE_VM_NAME" --query powerState -o tsv) || state="unknown"
          echo "Current state: $state"

          if [ "$state" != "VM running" ]; then
            echo "Starting VM..."
            az vm start -g "$INPUT_AZURE_RESOURCE_GROUP_NAME" -n "$INPUT_AZURE_VM_NAME"
          else
            echo "VM already running."
          fi
        elif [ "$INPUT_OPERATION" = "deallocate" ]; then
          echo "Deallocating VM..."
          az vm deallocate -g "$INPUT_AZURE_RESOURCE_GROUP_NAME" -n "$INPUT_AZURE_VM_NAME"
        fi

        echo "Final power state:"
        az vm get-instance-view \
          -g "$INPUT_AZURE_RESOURCE_GROUP_NAME" \
          -n "$INPUT_AZURE_VM_NAME" \
          --query "instanceView.statuses[?starts_with(code,'PowerState/')].displayStatus" \
          -o tsv
